name: gcare
description: A new Flutter project.
publish_to: none

version: 1.1.6+10

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  get_it: ^7.6.0
  dartz: ^0.10.1
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  go_router: ^6.5.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path: 1.8.2
  bot_toast: ^4.1.3
  connectivity_plus: ^4.0.2
  http: ^0.13.6
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.7
  package_info_plus: ^4.2.0
  flutter_markdown: ^0.6.14
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  device_preview: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - assets/
